version: '3'
services:
  converter:
    image: amdf/imgtengwar
    ports:
      - 3333:8081
      - 50051:50051
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 3334:8080      
    environment:
      - BASE_URL=/swagger
      - SWAGGER_JSON=/svc/svc.swagger.json
    volumes:      
       - ./svc:/svc

